- config:
    - hostname: 'localhost:8443'
- common:
  - headers: {"app-id": "4894f63625ed4dfc809b11ac42c2ae8b", "Services-Source-Type": "SDSS-Web", "Accept": "application/json"}
- tests:
  - test:
    - name: "Search by keyword"
    - url: "/services/search/duvet.do"
    - method: "GET" # for GETs this tag is not required, if field is not provided then GET is the default behavior
    - validations: # if additional json validation is needed,  basic validation is a 200 response code
      - compare: {"messages": "status", "expected":"SUCCESS", "comparator": "contains"}
      - compare: {"messages": "detail", "expected":"WHATEVER", "comparator": "contains"} # this will fail
  - test:
    - name: "Search ensembles by keyword"
    - url: "/services/search/sheets/ensembles.do"
    - method: "GET"
    - validations:
      - compare: {"messages": "status", "expected":"SUCCESS", "comparator": "contains"}
      - compare: {"values": "brand_name", "expected":"Starter", "comparator": "contains"}
      - compare: {"values": "refinement_Type_id", "expected":"3", "comparator": "contains"} #sometimes this fails, not due to the test, the response is not consistent
      - compare: {"values": "display_price", "expected":"$70.00", "comparator": "contains"}
      - compare: {"values": "page_Size", "expected":24, "comparator": "contains"}
  - test: 
    - name: "Basic get"
    - url: "/api/person/"
#- test: 
#    - name: "Get single person"
#    - url: "/api/person/1/"
#- test: 
#    - name: "Delete a single person, verify that works"
#    - url: "/api/person/1/"
#    - method: 'DELETE'
#- test: # create entity by PUT
#    - name: "Create/update person"
#    - url: "/api/person/1/"
#    - method: "PUT"
#    - body: '{"first_name": "Gaius","id": 1,"last_name": "Baltar","login": "gbaltar"}'
#    - headers: {'Content-Type': 'application/json'}
#    - validators:  # This is how we do more complex testing!
#        - compare: {header: content-type, comparator: contains, expected:'json'}
#        - compare: {jsonpath_mini: 'login', expected: 'gbaltar'}  # JSON extraction
#        - compare: {raw_body:"", comparator:contains, expected: 'Baltar' }  # Tests on raw response
#- test: # create entity by POST
#    - name: "Create person"
#    - url: "/api/person/"
#    - method: "POST"
#    - body: '{"first_name": "William","last_name": "Adama","login": "theadmiral"}'
#    - headers: {Content-Type: application/json}


